### ISSUE TITLE
[Lookup Anything] add search view

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/StardewMods#3]
Create a way to search for a subject from anywhere.

For example, hold `F1` to bring up a search box with a dropdown of matches. Click one of the matches to pop up the normal lookup UI:

```
        ┌────────────┐
Search: │ A          │
        └────────────┘─┐
          │ Abigail    │
          │ Apple      │
          │ Apple Tree │
          │ Apricot    │
          │ ...        │
          └────────────┘
```

[Mentioned in the forums](http://community.playstarbound.com/threads/smapi-lookup-anything.122929/page-4#post-3036993).

**Comment by mattfeldman** [comment]
I've been taking a stab at this with @Pathoschild's help, so far I'm working on building a search index and started working on the UI:

![image](https://cloud.githubusercontent.com/assets/121500/19140539/e3f5e3a0-8b42-11e6-9e93-
bd54cddf037e.png)

**Comment by Pathoschild** [comment]
Reopened. This was incorrectly closed by GitHub when I merged my mod repositories together.

**Comment by Pathoschild** [comment]
I'm looking into this for an upcoming release. I [updated the code](https://user-images.githubusercontent.com/230581/74079553-0528ae00-4a07-11ea-8f80-c183a1a829cd.png) from PR #9, and it still works fine after a few tweaks:
> ![image](https://user-images.githubusercontent.com/230581/74079580-4620c280-4a07-11ea-9b98-08f1a9f4ece7.png)

A lot has changed since the original code was written in 2016; the new `SubjectFactory`  should make this much easier to finish.

**Comment by Pathoschild** [comment]
Added in the upcoming Lookup Anything 1.26.
